version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ec:9f:2e:aa:1f:c9:ab:49:57:8f:c0:cd:2e:5b:f3:b0"
      - checkout
      - run: yarn install
      - run: yarn test
  npm_publish:
    docker:
      - image: circleci/node:12
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ec:9f:2e:aa:1f:c9:ab:49:57:8f:c0:cd:2e:5b:f3:b0"
      - checkout
      - run:
          command: |
            COMMIT_MSG=$(git log --format=oneline -n 1 $CIRCLE_SHA1)
            if [[ $COMMIT_MSG == *"[npm-publish]"* ]]; then
              echo "[npm-publish] detected. No publish necessary 👊"
              circleci step halt
            fi
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: git config --global user.email "$GIT_AUTHOR_EMAIL"
      - run: git config --global user.name "$GIT_AUTHOR_NAME"
      - run: yarn run release
  tag_latest:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          command: |
            COMMIT_MSG=$(git log --format=oneline -n 1 $CIRCLE_SHA1)
            if [[ $COMMIT_MSG != *"[npm-publish]"* ]]; then
              echo "[npm-publish] not detected. Not a taggable commit"
              circleci step halt
            fi
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Tag latest
          command: npm dist-tag add $(node -p "require('./package.json').name")@$(npm v . dist-tags.beta) latest
workflows:
  version: 2
  do_build:
    jobs:
      #   - test:
      #       context: public_package_publish
      - npm_publish:
          #   requires:
          #     - test
          context: public_package_publish
          filters:
            branches:
              only:
                - master
      - tag_latest:
          context: public_package_publish
          requires:
            - npm_publish
          filters:
            branches:
              only:
                - master
